services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ../.data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=drop
      - POSTGRES_USER=drop
      - POSTGRES_DB=drop
  minio:
    # honestly no idea where this image comes from
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ../.data/s3:/data
    environment:
      - MINIO_ROOT_USER=drop
      - MINIO_ROOT_PASSWORD=drop
    command: server /data --console-address ":9001"