services:
  postgres:
    image: postgres:14-alpine
    user: "1000:1000"
    ports:
      - 5432:5432
    volumes:
      - ../.data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=drop
      - POSTGRES_USER=drop
      - POSTGRES_DB=drop