services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -d drop -U drop
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=drop
      - POSTGRES_USER=drop
      - POSTGRES_DB=drop
  drop:
    image: decduck/drop-oss:v0.2.0-beta
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3000:3000
    volumes:
      - ./library:/library
      - ./certs:/certs
      - ./objects:/objects
    environment:
      - DATABASE_URL=postgres://drop:drop@postgres:5432/drop
      - FS_BACKEND_PATH=/objects
      - CLIENT_CERTIFICATES=/certs
      - LIBRARY=/library
      - GIANT_BOMB_API_KEY=REPLACE_WITH_YOUR_KEY
